version: '3.8'

services:
  postgrest:
    image: postgrest/postgrest:latest
    container_name: inventory_postgrest
    restart: always
    network_mode: "host"
    environment:
      PGRST_DB_URI: "postgres://inventory_user:1234@localhost:5433/inventory_db"
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_JWT_SECRET: "super_secret_jwt_token_min_32_characters_long_for_postgrest"
      PGRST_SERVER_PORT: "3001"
